apiVersion: v1
kind: Service
metadata:
    name: backend-api-svc
spec:
    selector:
        app: backend-api
    ports:
        - port: 8080
          targetPort: 8080
          name: frontend
        - port: 50000
          targetPort: 50000
          name: agent

    type: LoadBalancer
