name: Build Docker

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

permissions:
    contents: read

jobs:
    build-push:
        name: Build Push to ECR
        runs-on: ubuntu-20.04
        environment: production

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build, tag, and push image to Amazon ECR
              id: build-image
              env:
                  ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
                  IMAGE_TAG: ${{ github.sha }}
              run: |
                  docker build -t ${{ env.ECR_REGISTRY }}/backend-api:${{ env.IMAGE_TAG }} .
                  docker build -t ${{ env.ECR_REGISTRY }}/backend-api:latest .
                  docker push ${{ env.ECR_REGISTRY }}/backend-api:${{ env.IMAGE_TAG }}
                  docker push ${{ env.ECR_REGISTRY }}/backend-api:latest
